name=str(input("enter your name: "))
matric =(input("matric: "))
DOB=(input("DOB: "))
level=(input("enter level: "))
year=(input("year: "))
age=(input("age: "))
dept=(input("dept: "))
weight=float(input("weight: "))
ismuslim=bool(input("are you a muslim: "))


print(type(name))
print(type(matric))
print(type(DOB))
print(type(level))
print(type(year))
print(type(age))
print(type(dept))
print(type(weight))
print(type(ismuslim))
